name: publish

on:
  release:
    types: [created]

env:
  node_version: 14

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: .npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci --cache .npm --prefer-offline
      - run: tsc
      - run: npm run lint:ci
      - run: npm test
      - name: Archive package.json
        uses: actions/upload-artifact@v2
        with:
          name: package.json
          path: package.json

  publish:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - run: rm package.json
      - name: Download prepared package.json
        uses: actions/download-artifact@v2
        with:
          name: package.json
      - name: Publish
        run: |
          export PUBLISHED_VERSION=$(jq -r '.version' package.json)
          npm publish --ignore-scripts --tag fvtt-${PUBLISHED_VERSION//-[0-9]*/}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
